# -*- coding: utf-8 -*-
"""pract.7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b5KtLbRk4SHFJMrpQ6PBNkoEmDoTu64T
"""

def coin_change(coins, amount):
    # dp[i] = minimum coins needed to make amount i
    dp = [float('inf')] * (amount + 1)

    # 0 coins are needed to make amount 0
    dp[0] = 0

    # Calculate minimum coins for every amount
    for i in range(1, amount + 1):
        for coin in coins:
            if coin <= i:
                dp[i] = min(dp[i], dp[i - coin] + 1)

    # If amount cannot be formed
    if dp[amount] == float('inf'):
        return -1

    return dp[amount]


# User input
coins = list(map(int, input("Enter coin denominations: ").split()))
amount = int(input("Enter the amount: "))

result = coin_change(coins, amount)

if result == -1:
    print("Change cannot be made")
else:
    print("Minimum number of coins required:", result)

